module.exports = {
  regionId: "所属区县",
  stationId: "所属林场",
  village: "村（管护站）名",
  group: "（社、林班）号",
  smallClass: "小班号",
  placeName: "小地名",
  smallClassArea: "小班面积（亩）",
  treeCompose: "树种组成",
  targetName: "防治对象名称",
  time: "监测时间",
  workGroup: "施工作业单位名称",
  fcXianyan: "伐除对象-显眼枯死松树",
  fcXixiao: "伐除对象-细小枯死松树",
  fcGaodudayuwu: "伐除对象-高度5厘米以上的树桩",
  fcChanzhe: "伐除对象-藤蔓或活树连着枯死树",
  fcFugai: "伐除对象-藤蔓覆盖的枯死松树",
  fcFengzhe: "伐除对象-风折风倒的枯死松树",
  fcHuoshao: "伐除对象-火烧、雷击枯死松树",
  fcXuanya: "伐除对象-悬崖边枯死松树",
  fcXuangua: "伐除对象-悬挂或地面的松树梢头",
  fcHuoshukuzhi: "伐除对象-活松树上枯死树枝",
  fcTotal:"伐除对象-伐除小计",
  jcFcFengzhe: "集材对象-风折风倒的枯死松树",
  jcFcSongshu: "集材对象-松树",
  jcFcSongmu: "集材对象-松木段",
  jcFcSongzhi: "集材对象-地上粗1厘米以上松枝",
  jcFcShaotou: "集材对象-松树梢头",
  jcFcTotal:"集材对象-伐除小计",
  jcYcCaogai: "集材对象-用草覆盖",
  jcYcKuye: "集材对象-用枯枝落叶覆盖",
  jcYcTurang: "集材对象-用土壤覆盖",
  jcYcTengman: "集材对象-用藤蔓覆盖的松材",
  jcYcDigou: "集材对象-隐藏于地沟",
  jcYcDongxue: "集材对象-洞穴中的松材",
  jcYcTotal:"集材对象-隐藏小计",
  fsSongzhi: "焚烧对象-未完全炭化的松枝",
  fsSongmu: "焚烧对象-未完全炭化的松木",
  fsSongcai: "焚烧对象-未点火的松材堆",
  fzFazhuang: "伐桩高度5厘米以下",
  fzBopi:"伐桩剥皮",
  fzJiahao: "在横断面上砍“+字”口",
  fzTouyao: "投药",
  fzShuliao: "覆盖塑料布",
  fzNitu: "覆盖泥土厚度2厘以上",
  fzTotal:"伐桩小计",
  fzNumber:"伐桩个数"
}
